//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.296
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameBasicClasses.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameBasicClasses.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap adventure_core_avatar_by_the_rebexorcist_d3gzj02 {
            get {
                object obj = ResourceManager.GetObject("adventure_core_avatar_by_the_rebexorcist_d3gzj02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap atlas_avatar_by_the_rebexorcist_d3i8r14 {
            get {
                object obj = ResourceManager.GetObject("atlas_avatar_by_the_rebexorcist_d3i8r14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap avvy_commish_frankchamturret_by_the_rebexorcist_d3krkra {
            get {
                object obj = ResourceManager.GetObject("avvy_commish_frankchamturret_by_the_rebexorcist_d3krkra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap batblue {
            get {
                object obj = ResourceManager.GetObject("batblue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap batred {
            get {
                object obj = ResourceManager.GetObject("batred", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap companion_cube_in_a_jar_by_shinobitokobot_d4ayx1u {
            get {
                object obj = ResourceManager.GetObject("companion_cube_in_a_jar_by_shinobitokobot_d4ayx1u", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap defective_turret_avatar_by_the_rebexorcist_d3h6odr {
            get {
                object obj = ResourceManager.GetObject("defective_turret_avatar_by_the_rebexorcist_d3h6odr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap emotion_core_avatar_by_the_rebexorcist_d3h0qpp {
            get {
                object obj = ResourceManager.GetObject("emotion_core_avatar_by_the_rebexorcist_d3h0qpp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap fact_core_avatar_by_the_rebexorcist_d3h18dn {
            get {
                object obj = ResourceManager.GetObject("fact_core_avatar_by_the_rebexorcist_d3h18dn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap frankenturret_avatar_by_the_rebexorcist_d3hmbaw {
            get {
                object obj = ResourceManager.GetObject("frankenturret_avatar_by_the_rebexorcist_d3hmbaw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap free__aperture_icon__by_blueberryscarf_d42dwps {
            get {
                object obj = ResourceManager.GetObject("free__aperture_icon__by_blueberryscarf_d42dwps", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap free_avatar___portal_2_irony_by_jellosie_d498aes {
            get {
                object obj = ResourceManager.GetObject("free_avatar___portal_2_irony_by_jellosie_d498aes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap free_companion_cube_icon_by_ashunnoodles_d4w979m {
            get {
                object obj = ResourceManager.GetObject("free_companion_cube_icon_by_ashunnoodles_d4w979m", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap glowing_companion_cube_icon_by_pepperfox23_d319441 {
            get {
                object obj = ResourceManager.GetObject("glowing_companion_cube_icon_by_pepperfox23_d319441", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap oracle_turret_avatar_by_the_rebexorcist_d3h9ts8 {
            get {
                object obj = ResourceManager.GetObject("oracle_turret_avatar_by_the_rebexorcist_d3h9ts8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap portal_2_jumping_cube_icon_by_thebrokenegg_d3fzgwo {
            get {
                object obj = ResourceManager.GetObject("portal_2_jumping_cube_icon_by_thebrokenegg_d3fzgwo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap portal_2_turret_defending_icon_by_thebrokenegg_d3fdjxe {
            get {
                object obj = ResourceManager.GetObject("portal_2_turret_defending_icon_by_thebrokenegg_d3fdjxe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap portal_companion_cube_free_3_by_vanillascream_d3ijo9p {
            get {
                object obj = ResourceManager.GetObject("portal_companion_cube_free_3_by_vanillascream_d3ijo9p", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap portal_companion_cube_free_icon_by_firedragon47_d4np10j {
            get {
                object obj = ResourceManager.GetObject("portal_companion_cube_free_icon_by_firedragon47_d4np10j", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap portal_turret_icon_3_by_squeekbot_d3gwm7t {
            get {
                object obj = ResourceManager.GetObject("portal_turret_icon_3_by_squeekbot_d3gwm7t", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap portalMalus {
            get {
                object obj = ResourceManager.GetObject("portalMalus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap potados_by_sungoddessokami_d481k83 {
            get {
                object obj = ResourceManager.GetObject("potados_by_sungoddessokami_d481k83", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap soprano_turret_avatar_by_the_rebexorcist_d3h9k81 {
            get {
                object obj = ResourceManager.GetObject("soprano_turret_avatar_by_the_rebexorcist_d3h9k81", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap space_core_avatar_by_the_rebexorcist_d3h0wyn {
            get {
                object obj = ResourceManager.GetObject("space_core_avatar_by_the_rebexorcist_d3h0wyn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
