//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.296
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameBasicClasses.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameBasicClasses.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.IO.UnmanagedMemoryStream _4359__noisecollector__pongblipf4 {
            get {
                return ResourceManager.GetStream("_4359__noisecollector__pongblipf4", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream _4360__noisecollector__ponblipg_5 {
            get {
                return ResourceManager.GetStream("_4360__noisecollector__ponblipg_5", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream _4361__noisecollector__pongblipa_3 {
            get {
                return ResourceManager.GetStream("_4361__noisecollector__pongblipa_3", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream _4362__noisecollector__pongblipa_4 {
            get {
                return ResourceManager.GetStream("_4362__noisecollector__pongblipa_4", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream _4363__noisecollector__pongblipa3 {
            get {
                return ResourceManager.GetStream("_4363__noisecollector__pongblipa3", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream _4364__noisecollector__pongblipa4 {
            get {
                return ResourceManager.GetStream("_4364__noisecollector__pongblipa4", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream _4365__noisecollector__pongblipa5 {
            get {
                return ResourceManager.GetStream("_4365__noisecollector__pongblipa5", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream _4366__noisecollector__pongblipb3 {
            get {
                return ResourceManager.GetStream("_4366__noisecollector__pongblipb3", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream _4367__noisecollector__pongblipb4 {
            get {
                return ResourceManager.GetStream("_4367__noisecollector__pongblipb4", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream _4368__noisecollector__pongblipc_3 {
            get {
                return ResourceManager.GetStream("_4368__noisecollector__pongblipc_3", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream _4369__noisecollector__pongblipc_4 {
            get {
                return ResourceManager.GetStream("_4369__noisecollector__pongblipc_4", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream _4370__noisecollector__pongblipc_5 {
            get {
                return ResourceManager.GetStream("_4370__noisecollector__pongblipc_5", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream _4371__noisecollector__pongblipc4 {
            get {
                return ResourceManager.GetStream("_4371__noisecollector__pongblipc4", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream _4372__noisecollector__pongblipc5 {
            get {
                return ResourceManager.GetStream("_4372__noisecollector__pongblipc5", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream _4373__noisecollector__pongblipf3 {
            get {
                return ResourceManager.GetStream("_4373__noisecollector__pongblipf3", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream _4374__noisecollector__pongblipf5 {
            get {
                return ResourceManager.GetStream("_4374__noisecollector__pongblipf5", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream _4375__noisecollector__pongblipg_3 {
            get {
                return ResourceManager.GetStream("_4375__noisecollector__pongblipg_3", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream _4376__noisecollector__pongblipg_4 {
            get {
                return ResourceManager.GetStream("_4376__noisecollector__pongblipg_4", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream _4377__noisecollector__pongblipg3 {
            get {
                return ResourceManager.GetStream("_4377__noisecollector__pongblipg3", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream _4378__noisecollector__pongblipg4 {
            get {
                return ResourceManager.GetStream("_4378__noisecollector__pongblipg4", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream _4379__noisecollector__pongblipg5 {
            get {
                return ResourceManager.GetStream("_4379__noisecollector__pongblipg5", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream _4380__noisecollector__pongblipd_3 {
            get {
                return ResourceManager.GetStream("_4380__noisecollector__pongblipd_3", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream _4381__noisecollector__pongblipd_4 {
            get {
                return ResourceManager.GetStream("_4381__noisecollector__pongblipd_4", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream _4382__noisecollector__pongblipd_5 {
            get {
                return ResourceManager.GetStream("_4382__noisecollector__pongblipd_5", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream _4383__noisecollector__pongblipd3 {
            get {
                return ResourceManager.GetStream("_4383__noisecollector__pongblipd3", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream _4384__noisecollector__pongblipd4 {
            get {
                return ResourceManager.GetStream("_4384__noisecollector__pongblipd4", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream _4385__noisecollector__pongblipd5 {
            get {
                return ResourceManager.GetStream("_4385__noisecollector__pongblipd5", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream _4386__noisecollector__pongblipe3 {
            get {
                return ResourceManager.GetStream("_4386__noisecollector__pongblipe3", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream _4387__noisecollector__pongblipe4 {
            get {
                return ResourceManager.GetStream("_4387__noisecollector__pongblipe4", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream _4388__noisecollector__pongblipe5 {
            get {
                return ResourceManager.GetStream("_4388__noisecollector__pongblipe5", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream _4389__noisecollector__pongblipf_3 {
            get {
                return ResourceManager.GetStream("_4389__noisecollector__pongblipf_3", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream _4390__noisecollector__pongblipf_4 {
            get {
                return ResourceManager.GetStream("_4390__noisecollector__pongblipf_4", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream _4391__noisecollector__pongblipf_5 {
            get {
                return ResourceManager.GetStream("_4391__noisecollector__pongblipf_5", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap ball_disco2 {
            get {
                object obj = ResourceManager.GetObject("ball_disco2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap balle {
            get {
                object obj = ResourceManager.GetObject("balle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap barre {
            get {
                object obj = ResourceManager.GetObject("barre", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bat {
            get {
                object obj = ResourceManager.GetObject("bat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap batblue {
            get {
                object obj = ResourceManager.GetObject("batblue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap batred {
            get {
                object obj = ResourceManager.GetObject("batred", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bokeh_paws___texture_by_happymoonwolf_d4h64ph {
            get {
                object obj = ResourceManager.GetObject("bokeh_paws___texture_by_happymoonwolf_d4h64ph", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap brick {
            get {
                object obj = ResourceManager.GetObject("brick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bug1 {
            get {
                object obj = ResourceManager.GetObject("bug1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bug2 {
            get {
                object obj = ResourceManager.GetObject("bug2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bug3 {
            get {
                object obj = ResourceManager.GetObject("bug3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bug4 {
            get {
                object obj = ResourceManager.GetObject("bug4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Disco_Balls_by_nightmares06 {
            get {
                object obj = ResourceManager.GetObject("Disco_Balls_by_nightmares06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.IO.UnmanagedMemoryStream explosion {
            get {
                return ResourceManager.GetStream("explosion", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap flyingsaucer1 {
            get {
                object obj = ResourceManager.GetObject("flyingsaucer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap flyingsaucer2 {
            get {
                object obj = ResourceManager.GetObject("flyingsaucer2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap flyingsaucer3 {
            get {
                object obj = ResourceManager.GetObject("flyingsaucer3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap flyingsaucer4 {
            get {
                object obj = ResourceManager.GetObject("flyingsaucer4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.IO.UnmanagedMemoryStream gameMusic {
            get {
                return ResourceManager.GetStream("gameMusic", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap heart___star_bokeh_texture_1_by_yuripanda_d352a69 {
            get {
                object obj = ResourceManager.GetObject("heart___star_bokeh_texture_1_by_yuripanda_d352a69", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap heart_pattern_bokeh_texture_by_yuripanda_d35yx5r {
            get {
                object obj = ResourceManager.GetObject("heart_pattern_bokeh_texture_by_yuripanda_d35yx5r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap laser2 {
            get {
                object obj = ResourceManager.GetObject("laser2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.IO.UnmanagedMemoryStream laserFire {
            get {
                return ResourceManager.GetStream("laserFire", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream menuMusic {
            get {
                return ResourceManager.GetStream("menuMusic", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap pokeball {
            get {
                object obj = ResourceManager.GetObject("pokeball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap satellite1 {
            get {
                object obj = ResourceManager.GetObject("satellite1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap satellite2 {
            get {
                object obj = ResourceManager.GetObject("satellite2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap satellite3 {
            get {
                object obj = ResourceManager.GetObject("satellite3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap satellite4 {
            get {
                object obj = ResourceManager.GetObject("satellite4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap spaceship1 {
            get {
                object obj = ResourceManager.GetObject("spaceship1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap spaceship2 {
            get {
                object obj = ResourceManager.GetObject("spaceship2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap spaceship3 {
            get {
                object obj = ResourceManager.GetObject("spaceship3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap spaceship4 {
            get {
                object obj = ResourceManager.GetObject("spaceship4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap star1 {
            get {
                object obj = ResourceManager.GetObject("star1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap star2 {
            get {
                object obj = ResourceManager.GetObject("star2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap star3 {
            get {
                object obj = ResourceManager.GetObject("star3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap star4 {
            get {
                object obj = ResourceManager.GetObject("star4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap watchit1 {
            get {
                object obj = ResourceManager.GetObject("watchit1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap watchit2 {
            get {
                object obj = ResourceManager.GetObject("watchit2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap watchit3 {
            get {
                object obj = ResourceManager.GetObject("watchit3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap watchit4 {
            get {
                object obj = ResourceManager.GetObject("watchit4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
